CREATE TABLE Customer (
    CustomerId SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    BirthDate DATE NOT NULL,
    AddressId INTEGER NOT NULL REFERENCES Address(AddressId),
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)